# Vectorization

In [90]:
import numpy as np
import time
x_train = np.array([10,20,30])
w = np.array([100,200,300])

In [6]:
dot_prdt = np.dot(w,x_train)

In [7]:
dot_prdt

14000

Here dot operator multiplies each element of x_train vector into each element of vector w and finally adds up all the elements.
This happens parallelly. If there are more number of elements in the vector(array) then dot product is more effecient than conventional for-loop

## Vectors
Vectors are arrays with numbers. It will  have a single type, for example it does not contain character and number in a single vector.
Number of elements in the vector is called the Rank or dimention.  for example, the $0^{th}$ element, of the vector $\mathbf{x}$ is $x_0$. 

### Vector creation using numpy

In [20]:
a = np.zeros(4,); print(f"np.zeros(4,) a : {a}")
a = np.zeros(4); print(f"np.zeros(4) a : {a}")
a = np.random.random_sample(4)
a.dtype


np.zeros(4,) a : [0. 0. 0. 0.]
np.zeros(4) a : [0. 0. 0. 0.]


dtype('float64')

In [33]:
b = np.arange(10.)
print(f"np.arange(4) b: {b}")
print(f"np.shape() : {b.shape}")
print(f"np.dtype : {b.dtype}")

np.arange(4) b: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
np.shape() : (10,)
np.dtype : float64


### vector indexing 1-dimentional

In [40]:
a = np.arange(10)
print(f"a[1] is a scalar : {a[1]}")
# accessing one element will return scalar
a[2].shape

a[1] is a scalar : 1


()

In [41]:
try:
    c = a[10]
except Exception as e:
    print(f"error is {e}")

error is index 10 is out of bounds for axis 0 with size 10


### vector slicing

In [44]:
# a = np.arange(10)
print(f"a is {a}")
a[2:5:1]

a is [0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4])

In [52]:
d = np.arange(0,10)
print("d array is :", d)
d[1:2:1]

d array is : [0 1 2 3 4 5 6 7 8 9]


array([1])

 [start:stop:increments]
 starting of the index
 stop at which length 
 how many increments

In [58]:
d[2:6:3]

array([2, 5])

In [57]:
d[2:6:1]

array([2, 3, 4, 5])

In [59]:
d[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [60]:
d[:3]

array([0, 1, 2])

In [62]:
d[::2]

array([0, 2, 4, 6, 8])

### single vector operations : sum multiply negate

In [65]:
a = np.random.rand(4)
b = -a
b

array([-0.65745128, -0.17918324, -0.34773536, -0.77604086])

In [68]:
b = a.sum()
b

1.9604107389589447

In [75]:
# this is vector scalar operation
b = a +1
b

array([1, 2, 3, 4])

In [71]:
b = a*0
b

array([0., 0., 0., 0.])

### vector vector operations

In [73]:
a = np.arange(4)
b = np.arange(4)
print("a and b are " , a , b)
a*b

a and b are  [0 1 2 3] [0 1 2 3]


array([0, 1, 4, 9])

In [74]:
c = np.arange(3)
try:
    d = a + c
except Exception as e:
    print("exception is ", e)

exception is  operands could not be broadcast together with shapes (4,) (3,) 


### vector dot product
The dot product multiplies the values in two vectors element-wise and then sums the result.
Vector dot product requires the dimensions of the two vectors to be the same. 

In [83]:
rng = np.random.default_rng()
a = rng.integers(low=0, high=10, size=5)  
b = rng.integers(low=0, high=10, size=5)  
print(f"a is {a} b is {b}")

a is [3 6 8 4 8] b is [4 8 3 3 6]


In [86]:
def compute_dot(a,b):
    m = a.shape[0]
    dot_prdct = 0
    for i in range(m):
        dot_prdct = dot_prdct + a[i] * b [i]
    return dot_prdct


In [87]:
compute_dot(a,b)

144

#### using np.dot 

In [107]:
def comput_np_dot(a,b):
    dot_prdct = np.dot(a,b)
    #print(f"dot product of a and b vectors using np.dot(a,b) : {dot_prdct}")
    return dot_prdct

In [109]:
a = rng.integers(low=0,high=10000,size=10000)
b = rng.integers(low=0,high=10000,size=10000)
tic = time.time()
compute_dot(a,b)
toc = time.time()
print(f"time taken to compute dot product using conventional method is {toc-tic}")
tic= time.time()
comput_np_dot(a,b)
toc=time.time()
print(f"time taken to compute dot product using np.dot method is {toc-tic}")

time taken to compute dot product using conventional method is 0.00753331184387207
time taken to compute dot product using np.dot method is 0.0


In [117]:
x = np.arange(5)
w = np.array([2])
c = np.dot(x[2],w)
c.shape

(1,)

## Multi dimentional vector

In [135]:
a = np.zeros((2,3))
print(f"a is a multi dimentional matrics of shape m,n 2,3 {a}")
b= np.random.random_sample((3,2))
c = rng.integers(low=0,high=20,size=(4,3))
c.shape

a is a multi dimentional matrics of shape m,n 2,3 [[0. 0. 0.]
 [0. 0. 0.]]


(4, 3)

#### indexing

In [151]:
print(c)
c[1:3:1]

[[ 2 18  3]
 [ 1 10 11]
 [ 8 10  5]
 [ 3  0 16]]


array([[ 1, 10, 11],
       [ 8, 10,  5]], dtype=int64)

In [163]:
e = np.arange(6).reshape(2,3)
e

array([[0, 1, 2],
       [3, 4, 5]])

In [165]:
e.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [168]:
f = np.arange(20).reshape(-1, 10)
g = np.arange(20).reshape(2,10)
g

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [176]:
g[0,1:4]

array([1, 2, 3])